language: objective-c
osx_image: xcode10.2

script:
- xcodebuild test -project HottPotato.xcodeproj -scheme HottPotatoTests -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.0'
- pod lib lint --allow-warnings

before_install:
- gem install cocoapods --no-document --quiet
